name 'rexcore'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rexcore'
long_description 'Installs/Configures rexcore'
version '0.2.1'

depends 'chocolatey'
depends 'chef-client'
depends 'push-jobs'
depends 'hostsfile'
